//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveWish
    {
        public int id { get; set; }
        public int IDmachine { get; set; }
        public int IDStaff { get; set; }
        public int IDPowder { get; set; }
        public string Drying { get; set; }
        public string Status { get; set; }
        public string Branch { get; set; }
    }
}
